### PR TITLE
add Ancient Beast to the list

### PR DESCRIPTION
**Pull request by tsabitahh**
I added Ancient Beast to the Turned-based Strategy category as it requested by its developers.

### CODE REVIEW

**Comment by DreadKnight** [comment]
Nice initiative. Description will need to be revamped, as it's a bit lulz 😆

**Comment by DreadKnight** [comment]
Please edit the description to this:

Spiritual successor to Heroes of Might and Magic III focusing on combat; matched based eSport.

**Comment by tsabitahh** [comment]
I'll edit it right away!

**Comment by DreadKnight** [comment]
PR has merge conflict because while this is waiting for 2 months now, someone else made an issue recently #45 and another game was added in the exact same spot right away 🐻

**Pull request closed without merging**
