### PR TITLE
Add Ancient Beast

### PR DESCRIPTION
**Pull request by tsabitahh**

### CODE REVIEW

**Comment by DreadKnight** [comment]
This adds https://ancientbeast.com / https://github.com/FreezingMoon/AncientBeast and fixes #46

**Comment by DreadKnight** [comment]
🐻

**Comment by DreadKnight** [comment]
Checked the code better, this lacked the proper formatting. Will make PR myself, hopefully it will get merged 🤞🏻

**Comment by tsabitahh** [comment]
Thank you! I planned to redo everything but you have solved the issue already. I'll do my best to learn more.

**Pull request closed without merging**
